-- Milestone 3: tasks domain. Portable SQL (PostgreSQL + H2 PostgreSQL-mode).
-- Owner is a user FK with ON DELETE CASCADE; enums are constrained strings mirrored by CHECKs.

CREATE TABLE tasks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT       NOT NULL,
    title           VARCHAR(200) NOT NULL,
    description     VARCHAR(2000),
    status          VARCHAR(20)  NOT NULL DEFAULT 'TODO',
    priority        VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    estimated_hours NUMERIC(6,2),
    due_date        DATE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_tasks_status CHECK (status IN ('TODO','IN_PROGRESS','COMPLETED','CANCELLED')),
    CONSTRAINT chk_tasks_priority CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT chk_tasks_estimated_hours CHECK (estimated_hours IS NULL OR estimated_hours >= 0)
);

CREATE INDEX idx_tasks_owner_id         ON tasks (owner_id);
CREATE INDEX idx_tasks_owner_created_at ON tasks (owner_id, created_at);
CREATE INDEX idx_tasks_owner_status     ON tasks (owner_id, status);
CREATE INDEX idx_tasks_owner_priority   ON tasks (owner_id, priority);
CREATE INDEX idx_tasks_owner_due_date   ON tasks (owner_id, due_date);
