-- Milestone 3: customers domain. Portable SQL (PostgreSQL + H2 PostgreSQL-mode).
-- UNIQUE(owner_id, email) prevents duplicate customer emails per owner; NULL emails are allowed
-- multiple times (NULLs are distinct in both PostgreSQL and H2).

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL,
    name       VARCHAR(150) NOT NULL,
    email      VARCHAR(255),
    phone      VARCHAR(30),
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_customers_owner_email UNIQUE (owner_id, email),
    CONSTRAINT chk_customers_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE INDEX idx_customers_owner_id         ON customers (owner_id);
CREATE INDEX idx_customers_owner_created_at ON customers (owner_id, created_at);
