-- Milestone 9: durable agent audit & execution history. Portable SQL (PostgreSQL + H2 PG-mode).
-- Three typed tables (no generic events table): one execution per run, ordered steps, tool executions.
-- Written from backend-observed facts (never the LLM); owner-scoped; UUID natural keys give idempotency.
-- Stores safe metadata + hashes + bounded summaries only — never raw prompts, arguments, LLM output,
-- chain-of-thought, or secrets (see docs/DATA_PRIVACY.md, docs/AUDIT_LOGGING.md).

CREATE TABLE agent_executions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_uid          VARCHAR(36)  NOT NULL,
    owner_id               BIGINT       NOT NULL,
    conversation_id        VARCHAR(36),
    request_id             VARCHAR(36),
    status                 VARCHAR(24)  NOT NULL,
    iterations             INTEGER      NOT NULL DEFAULT 0,
    tool_calls             INTEGER      NOT NULL DEFAULT 0,
    failure_code           VARCHAR(48),
    final_response_summary VARCHAR(600),
    started_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at           TIMESTAMP WITH TIME ZONE,
    duration_ms            BIGINT,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agent_executions_uid UNIQUE (execution_uid),
    CONSTRAINT fk_agent_executions_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_agent_executions_status CHECK (status IN
        ('STARTED','RUNNING','COMPLETED','FAILED','TIMED_OUT','CANCELLED',
         'LIMIT_REACHED','LOOP_DETECTED','PENDING_CONFIRMATION','BLOCKED'))
);

CREATE INDEX idx_agent_exec_owner_started ON agent_executions (owner_id, started_at DESC);
CREATE INDEX idx_agent_exec_owner_conv    ON agent_executions (owner_id, conversation_id);
CREATE INDEX idx_agent_exec_owner_status  ON agent_executions (owner_id, status);

CREATE TABLE agent_steps (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT      NOT NULL,
    sequence     INTEGER     NOT NULL,
    step_type    VARCHAR(24) NOT NULL,
    status       VARCHAR(16) NOT NULL,
    tool_name    VARCHAR(100),
    detail_code  VARCHAR(48),
    started_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    duration_ms  BIGINT,
    CONSTRAINT uq_agent_steps_exec_seq UNIQUE (execution_id, sequence),
    CONSTRAINT fk_agent_steps_execution FOREIGN KEY (execution_id) REFERENCES agent_executions (id) ON DELETE CASCADE,
    CONSTRAINT chk_agent_steps_type CHECK (step_type IN
        ('LLM_DECISION','GUARDRAIL','TOOL_CALL','CONFIRMATION_REQUIRED',
         'CONFIRMATION_APPROVED','CONFIRMATION_REJECTED','FINAL','FAILURE')),
    CONSTRAINT chk_agent_steps_status CHECK (status IN ('OK','FAILED','BLOCKED','REQUIRED'))
);

CREATE INDEX idx_agent_steps_execution ON agent_steps (execution_id);

CREATE TABLE tool_executions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_execution_uid VARCHAR(36)  NOT NULL,
    step_id            BIGINT       NOT NULL,
    execution_id       BIGINT       NOT NULL,
    owner_id           BIGINT       NOT NULL,
    tool_name          VARCHAR(100) NOT NULL,
    risk_level         VARCHAR(16)  NOT NULL,
    outcome            VARCHAR(24)  NOT NULL,
    error_code         VARCHAR(48),
    confirmation_id    VARCHAR(36),
    arguments_hash     CHAR(64),
    result_summary     VARCHAR(600),
    started_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at       TIMESTAMP WITH TIME ZONE,
    duration_ms        BIGINT,
    CONSTRAINT uq_tool_executions_uid UNIQUE (tool_execution_uid),
    CONSTRAINT fk_tool_executions_step FOREIGN KEY (step_id) REFERENCES agent_steps (id) ON DELETE CASCADE,
    CONSTRAINT fk_tool_executions_execution FOREIGN KEY (execution_id) REFERENCES agent_executions (id) ON DELETE CASCADE,
    CONSTRAINT fk_tool_executions_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_tool_executions_risk CHECK (risk_level IN
        ('READ_ONLY','DETERMINISTIC','SIDE_EFFECTING','HIGH_RISK')),
    CONSTRAINT chk_tool_executions_outcome CHECK (outcome IN
        ('SUCCESS','FAILED','DENIED','NOT_EXECUTED','CONFIRMATION_REQUIRED','TIMEOUT'))
);

CREATE INDEX idx_tool_exec_owner_started ON tool_executions (owner_id, started_at DESC);
CREATE INDEX idx_tool_exec_execution     ON tool_executions (execution_id);
CREATE INDEX idx_tool_exec_tool          ON tool_executions (tool_name);
